"""Service layer for the generated project."""
from typing import List, Optional

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware

from .models import SiliconStat, SiliconStatCreate, SiliconStatUpdate
from .store import store

app = FastAPI(
    title="Tutorial SemiScale Alpha (or SiliconStat) API",
    version="0.1.0",
    description="REST API for Tutorial SemiScale Alpha (or SiliconStat). Generated by the Agentic SDLC workflow.",
    docs_url="/docs",
    openapi_url="/openapi.json",
    openapi_tags=[
        {"name": "health", "description": "Liveness probe used by the deploy pipeline."},
        {"name": "siliconstats", "description": "SiliconStats managed by this service."},
    ],
)

# The UI is a separate App Service, so it is a cross-origin caller.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health", tags=["health"])
def health() -> dict:
    return {"status": "ok"}


@app.get("/api/siliconstats", response_model=List[SiliconStat], tags=["siliconstats"])
def list_items(status: Optional[str] = Query(default=None)) -> List[dict]:
    return store.list(status)


@app.post("/api/siliconstats", response_model=SiliconStat, status_code=201, tags=["siliconstats"])
def create_item(body: SiliconStatCreate) -> dict:
    return store.create(body.model_dump())


@app.get("/api/siliconstats/{item_id}", response_model=SiliconStat, tags=["siliconstats"])
def get_item(item_id: int) -> dict:
    item = store.get(item_id)
    if item is None:
        raise HTTPException(status_code=404, detail="SiliconStat not found")
    return item


@app.patch("/api/siliconstats/{item_id}", response_model=SiliconStat, tags=["siliconstats"])
def update_item(item_id: int, body: SiliconStatUpdate) -> dict:
    item = store.update(item_id, body.model_dump())
    if item is None:
        raise HTTPException(status_code=404, detail="SiliconStat not found")
    return item


@app.delete("/api/siliconstats/{item_id}", status_code=204, tags=["siliconstats"])
def delete_item(item_id: int) -> None:
    if not store.delete(item_id):
        raise HTTPException(status_code=404, detail="SiliconStat not found")
